### ISSUE TITLE
Allow removing multihashes and metadata from dhstore

### ISSUE THREAD

**Issue by ischasny** [ipni/dhstore#26]
We allow opportunistic clean up of records in `storetheindex`. In the same way we need to proxy these removes from `storetheindex` through `go-indexer-core` and into `dhstore`.
* allow opportunistic clean up of multihashes
* allow clean up of metadata

**Comment by gammazero** [comment]
Metadata is currently deleted directly by storetheindex when a removal advertisement is processed.

Opportunistic delete would be done when encountering a value key that is no longer found, and then deleting the dh-multihash that was used for the original lookup. Unfortunately, the dh-multihash is not available at this point.  The dh-multihash is used to look up an encrypted-value-key (evk). The evk is returned to the client where it is decrypted to get the value-key (vk). The vk is then used to look up the metadata and provider information. If the vk is not found, there is no good way to recover the dh-multihash.

Instead, a garbage collection process is run. This scans each provider's advertisement chain to find removal advertisements. It then finds previous advertisements for the removed context ID, reads the multihashes from these ads, computes the dh-multihashs, and then deletes these.

@ischasny I think with GC in place, and metadata already being deleted, this issue can be closed.
